"""Project exporter - generates a deployable FastAPI project."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Environment

from instantapi.ai.detector import DetectionResult


# Inline templates (no external template files needed for MVP)
MAIN_PY_TEMPLATE = '''"""Auto-generated API by InstantAPI - {{ site_description }}"""

import math
from typing import Any

from fastapi import FastAPI, Query, HTTPException
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{{ title }}",
    description="{{ description }}",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Data ────────────────────────────────────────
{% for ep in endpoints %}
{{ ep.name }}_data = {{ ep.sample_data | tojson(indent=2) }}
{% endfor %}

# ─── Root ────────────────────────────────────────

@app.get("/")
async def root():
    return {
        "name": "{{ title }}",
        "source": "{{ source_url }}",
        "endpoints": [
            {% for ep in endpoints %}
            {"path": "/api/{{ ep.name }}", "description": "{{ ep.description }}"},
            {% endfor %}
        ],
    }

# ─── Endpoints ───────────────────────────────────
{% for ep in endpoints %}

@app.get("/api/{{ ep.name }}", tags=["{{ ep.name }}"])
async def list_{{ ep.name }}(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    q: str = Query(""),
):
    items = {{ ep.name }}_data.copy()
    if q:
        q_lower = q.lower()
        items = [i for i in items if any(q_lower in str(v).lower() for v in i.values())]
    total = len(items)
    start = (page - 1) * limit
    return {
        "data": items[start:start + limit],
        "pagination": {"page": page, "total": total, "total_pages": max(1, math.ceil(total / limit))},
    }


@app.get("/api/{{ ep.name }}/{item_id}", tags=["{{ ep.name }}"])
async def get_{{ ep.name }}_item(item_id: int):
    if item_id < 0 or item_id >= len({{ ep.name }}_data):
        raise HTTPException(404, "Not found")
    return {"data": {{ ep.name }}_data[item_id], "id": item_id}
{% endfor %}
'''

DOCKERFILE_TEMPLATE = '''FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''

REQUIREMENTS_TEMPLATE = """fastapi>=0.115.0
uvicorn[standard]>=0.30.0
"""

README_TEMPLATE = '''# {{ title }}

> Auto-generated REST API from [{{ source_url }}]({{ source_url }})

Generated by [InstantAPI](https://github.com/riri/instantapi)

## Quick Start

```bash
pip install -r requirements.txt
uvicorn main:app --reload
```

Open [http://localhost:8000/docs](http://localhost:8000/docs) for interactive API docs.

## Docker

```bash
docker build -t {{ title | lower | replace(" ", "-") }} .
docker run -p 8000:8000 {{ title | lower | replace(" ", "-") }}
```

## Endpoints

{% for ep in endpoints %}
### {{ ep.method }} /api/{{ ep.name }}

{{ ep.description }}

**Fields:** {{ ep.fields | join(", ") }}

{% endfor %}
'''


def export_project(result: DetectionResult, output_dir: str | Path) -> Path:
    """Export a full deployable FastAPI project.

    Args:
        result: Detection result with schemas and data.
        output_dir: Directory to write the project to.

    Returns:
        Path to the generated project directory.
    """
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    env = Environment(autoescape=False)

    title = result.site_description or f"API for {result.source_url}"

    # Prepare template context
    endpoints_ctx = []
    for ep in result.endpoints:
        endpoints_ctx.append({
            "name": ep.name,
            "description": ep.description,
            "method": ep.method,
            "sample_data": ep.sample_data,
            "fields": list(ep.schema_fields.keys()),
        })

    context: dict[str, Any] = {
        "title": title,
        "description": f"Auto-generated API from {result.source_url}",
        "site_description": result.site_description,
        "source_url": result.source_url,
        "endpoints": endpoints_ctx,
    }

    # Generate files
    files = {
        "main.py": MAIN_PY_TEMPLATE,
        "Dockerfile": DOCKERFILE_TEMPLATE,
        "requirements.txt": REQUIREMENTS_TEMPLATE,
        "README.md": README_TEMPLATE,
    }

    for filename, template_str in files.items():
        template = env.from_string(template_str)
        content = template.render(**context)
        (output / filename).write_text(content, encoding="utf-8")

    return output
