"""Dynamic FastAPI endpoint generator."""

from __future__ import annotations

import math
from typing import Any

from fastapi import FastAPI, Query, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from instantapi.ai.detector import DetectionResult, EndpointSchema


def create_api(result: DetectionResult) -> FastAPI:
    """Dynamically generate a FastAPI app from detected schemas.

    This is where the magic happens - we take the AI-detected schemas
    and create fully functional REST API endpoints with:
    - Listing with pagination
    - Single item by ID
    - Full-text search
    - Field filtering
    - Swagger/OpenAPI docs auto-generated

    Args:
        result: Detection result with endpoint schemas and sample data.

    Returns:
        A configured FastAPI application.
    """
    app = FastAPI(
        title=f"InstantAPI - {result.site_description or result.source_url}",
        description=(
            f"Auto-generated REST API from {result.source_url}\n\n"
            "Generated by [InstantAPI](https://github.com/riri/instantapi)"
        ),
        version="1.0.0",
    )

    # CORS - allow all origins for development
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Root endpoint with API overview
    @app.get("/", tags=["meta"])
    async def root() -> dict[str, Any]:
        return {
            "name": "InstantAPI",
            "source": result.source_url,
            "description": result.site_description,
            "endpoints": [
                {
                    "path": f"/api/{ep.name}",
                    "method": ep.method,
                    "description": ep.description,
                    "item_count": ep.item_count,
                    "fields": list(ep.schema_fields.keys()),
                }
                for ep in result.endpoints
            ],
            "docs": "/docs",
        }

    # Create endpoints for each detected data pattern
    for endpoint in result.endpoints:
        _register_endpoint(app, endpoint)

    return app


def _register_endpoint(app: FastAPI, endpoint: EndpointSchema) -> None:
    """Register CRUD-like endpoints for a detected data pattern."""
    data = endpoint.sample_data
    name = endpoint.name
    fields = list(endpoint.schema_fields.keys())

    # GET /api/{name} - List all items with pagination, search, filtering
    @app.get(
        f"/api/{name}",
        tags=[name],
        summary=f"List all {name}",
        description=endpoint.description,
    )
    async def list_items(
        page: int = Query(1, ge=1, description="Page number"),
        limit: int = Query(20, ge=1, le=100, description="Items per page"),
        q: str = Query("", description="Full-text search across all fields"),
        sort: str = Query("", description=f"Sort by field. Available: {', '.join(fields)}"),
        order: str = Query("asc", description="Sort order: asc or desc"),
    ) -> dict[str, Any]:
        items = data.copy()

        # Full-text search
        if q:
            q_lower = q.lower()
            items = [
                item
                for item in items
                if any(q_lower in str(v).lower() for v in item.values())
            ]

        # Sorting
        if sort and sort in fields:
            reverse = order.lower() == "desc"
            items = sorted(
                items,
                key=lambda x: str(x.get(sort, "")),
                reverse=reverse,
            )

        # Pagination
        total = len(items)
        total_pages = max(1, math.ceil(total / limit))
        start = (page - 1) * limit
        end = start + limit
        page_items = items[start:end]

        return {
            "data": page_items,
            "pagination": {
                "page": page,
                "limit": limit,
                "total": total,
                "total_pages": total_pages,
                "has_next": page < total_pages,
                "has_prev": page > 1,
            },
            "meta": {
                "endpoint": f"/api/{name}",
                "fields": fields,
            },
        }

    # GET /api/{name}/search - Advanced search
    @app.get(
        f"/api/{name}/search",
        tags=[name],
        summary=f"Search {name}",
    )
    async def search_items(
        q: str = Query(..., description="Search query"),
        field: str = Query("", description=f"Limit search to field. Available: {', '.join(fields)}"),
    ) -> dict[str, Any]:
        q_lower = q.lower()

        if field:
            results = [
                item
                for item in data
                if field in item and q_lower in str(item[field]).lower()
            ]
        else:
            results = [
                item
                for item in data
                if any(q_lower in str(v).lower() for v in item.values())
            ]

        return {
            "data": results,
            "query": q,
            "field": field or "all",
            "count": len(results),
        }

    # GET /api/{name}/schema - Get the schema for this endpoint
    @app.get(
        f"/api/{name}/schema",
        tags=[name],
        summary=f"Get schema for {name}",
    )
    async def get_schema() -> dict[str, Any]:
        return {
            "name": endpoint.name,
            "description": endpoint.description,
            "fields": {
                fn: {
                    "type": f.type,
                    "description": f.description,
                    "example": f.example,
                }
                for fn, f in endpoint.schema_fields.items()
            },
        }

    # GET /api/{name}/{id} - Get single item by index
    @app.get(
        f"/api/{name}/{{item_id}}",
        tags=[name],
        summary=f"Get {name} by ID",
    )
    async def get_item(
        item_id: int,
    ) -> dict[str, Any]:
        if item_id < 0 or item_id >= len(data):
            raise HTTPException(
                status_code=404,
                detail=f"{name} with id {item_id} not found",
            )
        return {"data": data[item_id], "id": item_id}
